---
version: "3.7"
services:
  mfer-node:
   build: .
   restart: unless-stopped
   command: '/run.sh'
   environment:
     - LISTEN=0.0.0.0:8545
     - UPSTREAM=${UPSTREAM}
     - MAXKEYS=${MAXKEYS}
     - BATCHSIZE=${BATCHSIZE}
     - LOGPATH=${LOGPATH} #leave blank for stdout

  rpc-proxy:
    build: https://github.com/sec-bit/mfer-node.git#rpc-proxy
    ports:
      - "${EXPOSE_PORT}:11111"
    environment:
      - TARGET=http://mfer-node:8545 # connect to mfer-node's rpc port
      - METHODS=${ALLOWED_METHODS}
      - LISTEN_ADDR=0.0.0.0 
      - LISTEN_PORT=11111 
    restart: unless-stopped
