---
version: "3.7"
services:
  mfer-node:
   build: .
   restart: unless-stopped
   command: '/run.sh'
   environment:
     - LISTEN=${LISTEN}
     - UPSTREAM=${UPSTREAM}
     - MAXKEYS=${MAXKEYS}
     - BATCHSIZE=${BATCHSIZE}
     - LOGPATH=${LOGPATH} #leave blank for stdout

  rpc-proxy:
    build: https://github.com/sec-bit/mfer-node.git#rpc-proxy
    ports:
      - "10545:10545"
    environment:
      - TARGET=http://mfer-node:10545
      - METHODS=mfer_traceTransactionBundle,eth_blockNumber
      - LISTEN_ADDR=0.0.0.0 
      - LISTEN_PORT=10545 
    restart: unless-stopped
