---
version: "3.7"
services:
  mfer-node:
   build: .
   ports: 
    - "8545:8545"
    - "10545:10545"
   restart: unless-stopped
   command: 'mfer-node --upstream https://rpc.ankr.com/eth'
   #Ankr is a freely accessible ethereum node, can be removed to be replaced by localhost:8545 as default or can be replaced to any other node url like self hosted/Infura/Alchemy etc.
