---
version: "3.7"
services:
  mfer-node:
   build: .
   restart: unless-stopped
   command: '/run.sh'
   environment:
     - LISTEN=0.0.0.0:10545
     - UPSTREAM=https://rpc.ankr.com/eth
     - MAXKEYS=100
     - BATCHSIZE=200

  rpc-proxy:
    build: https://github.com/sec-bit/mfer-node.git#rpc-proxy
    ports:
      - "10545:10545"
    environment:
      - TARGET=http://mfer-node:10545
      - METHODS=mfer_traceTransactionBundle,eth_blockNumber
      - LISTEN_ADDR=0.0.0.0 
      - LISTEN_PORT=10545 
    restart: unless-stopped
